import React, { useState } from 'react';
import { SHIKHAR_PROFILE, RESUME_RAW_TEXT } from '../data/shikharProfile';
import { 
  GraduationCap, 
  Briefcase, 
  MapPin, 
  Mail, 
  Phone, 
  FileText, 
  Copy, 
  Check, 
  ExternalLink, 
  Send, 
  Sparkles, 
  Award, 
  Code2, 
  Terminal,
  ShieldCheck,
  CheckCircle2,
  Download,
  Link2,
  Paperclip
} from 'lucide-react';
import { downloadResumeText, openPrintableResume } from '../utils/resumeDownload';

interface CandidateProfileTabProps {
  onOpenCvModal: () => void;
}

export const CandidateProfileTab: React.FC<CandidateProfileTabProps> = ({ onOpenCvModal }) => {
  const [copiedResume, setCopiedResume] = useState(false);
  const [copiedEmail, setCopiedEmail] = useState(false);
  const [downloaded, setDownloaded] = useState(false);
  const [resumeLink, setResumeLink] = useState(() => localStorage.getItem('shikhar_resume_link') || '');
  const [linkSaved, setLinkSaved] = useState(false);

  const handleCopyResume = () => {
    navigator.clipboard.writeText(RESUME_RAW_TEXT);
    setCopiedResume(true);
    setTimeout(() => setCopiedResume(false), 2000);
  };

  const handleCopyEmail = () => {
    navigator.clipboard.writeText(SHIKHAR_PROFILE.email);
    setCopiedEmail(true);
    setTimeout(() => setCopiedEmail(false), 2000);
  };

  const handleDownload = () => {
    downloadResumeText();
    setDownloaded(true);
    setTimeout(() => setDownloaded(false), 2500);
  };

  const handleSaveResumeLink = (val: string) => {
    setResumeLink(val);
    localStorage.setItem('shikhar_resume_link', val);
    setLinkSaved(true);
    setTimeout(() => setLinkSaved(false), 2000);
  };

  const testGmailComposeUrl = `https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(SHIKHAR_PROFILE.email)}&su=${encodeURIComponent('Test Outreach: Senior Software Developer (Bengaluru) — Shikhar Singhal | IIT Kharagpur')}&body=${encodeURIComponent(`Hi Shikhar,\n\nThis is a test outreach generated by your automated Job Application system.\n\nYour profile details:\n• Education: IIT Kharagpur (Dual Degree B.Tech + M.Tech)\n• Experience: 6+ Years (Current: Senior Software Developer at msg global PaPM Cloud, Bengaluru)\n• Core Stack: TypeScript, NestJS, BullMQ, Kafka, SAP HANA Cloud, Redis\n\nGmail integration is 100% active and configured to send from your account: ${SHIKHAR_PROFILE.email}.\n\nReady to dispatch applications to Bengaluru recruiters in seconds!`)}`;

  return (
    <div className="space-y-6">
      
      {/* Top Banner: Verification & Quick Action Bar */}
      <div className="bg-gradient-to-r from-zinc-900 to-indigo-950 rounded-2xl p-6 text-white shadow-md">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-indigo-500 to-blue-600 flex items-center justify-center font-black text-2xl text-white shadow-inner shrink-0">
              SS
            </div>
            <div>
              <div className="flex items-center gap-2 flex-wrap">
                <h2 className="text-xl sm:text-2xl font-black tracking-tight">{SHIKHAR_PROFILE.name}</h2>
                <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                  <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
                  Verified IIT KGP Profile
                </span>
              </div>
              <p className="text-sm text-zinc-300 mt-1">
                {SHIKHAR_PROFILE.currentTitle} • {SHIKHAR_PROFILE.currentCompany}
              </p>
              <div className="flex items-center gap-4 mt-2 text-xs text-zinc-400 flex-wrap">
                <span className="flex items-center gap-1">
                  <Mail className="w-3.5 h-3.5 text-indigo-400" />
                  {SHIKHAR_PROFILE.email}
                </span>
                <span className="flex items-center gap-1">
                  <Phone className="w-3.5 h-3.5 text-indigo-400" />
                  {SHIKHAR_PROFILE.phone}
                </span>
                <span className="flex items-center gap-1">
                  <MapPin className="w-3.5 h-3.5 text-indigo-400" />
                  {SHIKHAR_PROFILE.location}
                </span>
              </div>
            </div>
          </div>

          {/* Quick Actions */}
          <div className="flex flex-wrap items-center gap-2.5">
            <a
              href={testGmailComposeUrl}
              target="_blank"
              rel="noreferrer"
              className="px-4 py-2 rounded-xl text-xs font-bold bg-indigo-600 hover:bg-indigo-500 text-white shadow-sm inline-flex items-center gap-1.5 transition-colors"
              title="Test the 1-click Gmail compose flow with your own email"
            >
              <Send className="w-3.5 h-3.5" />
              <span>Test Send to My Gmail</span>
            </a>

            <button
              onClick={handleDownload}
              className="px-3 py-2 rounded-xl text-xs font-bold bg-white/10 hover:bg-white/20 text-white border border-white/20 inline-flex items-center gap-1.5 transition-colors cursor-pointer"
              title="Download resume to attach in emails"
            >
              <Download className="w-3.5 h-3.5 text-indigo-300" />
              <span>{downloaded ? 'Downloaded!' : 'Download Resume'}</span>
            </button>

            <button
              onClick={onOpenCvModal}
              className="px-4 py-2 rounded-xl text-xs font-bold bg-white/10 hover:bg-white/20 text-white border border-white/20 inline-flex items-center gap-1.5 transition-colors cursor-pointer"
            >
              <FileText className="w-3.5 h-3.5 text-indigo-300" />
              <span>View Full CV</span>
            </button>

            <a
              href="https://mail.google.com/mail/u/0/#sent"
              target="_blank"
              rel="noreferrer"
              className="px-3 py-2 rounded-xl text-xs font-semibold bg-zinc-800 hover:bg-zinc-700 text-zinc-300 border border-zinc-700 inline-flex items-center gap-1"
            >
              <span>Gmail Sent Box</span>
              <ExternalLink className="w-3 h-3 text-zinc-400" />
            </a>
          </div>
        </div>
      </div>

      {/* Resume File & Attachment Settings Bar */}
      <div className="bg-white rounded-2xl border border-zinc-200 p-4 shadow-xs flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-indigo-50 border border-indigo-100 flex items-center justify-center text-indigo-600 shrink-0">
            <Paperclip className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="font-bold text-sm text-zinc-900">Shikhar_Singhal_IIT_Kharagpur_Resume.pdf</span>
              <span className="text-[10px] font-semibold text-emerald-700 bg-emerald-100 px-2 py-0.5 rounded-full">
                Auto-Attached in Outreaches
              </span>
            </div>
            <p className="text-xs text-zinc-500 mt-0.5">
              Dual Degree IIT Kharagpur (Exploration Geophysics) • 6+ YOE Distributed Systems (NestJS, BullMQ, Kafka)
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 flex-wrap w-full md:w-auto">
          <button
            onClick={handleDownload}
            className="px-3 py-1.5 rounded-xl text-xs font-semibold bg-indigo-50 hover:bg-indigo-100 text-indigo-700 border border-indigo-200 inline-flex items-center gap-1.5 transition-colors cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span>{downloaded ? 'Downloaded!' : 'Download Resume (.txt)'}</span>
          </button>

          <button
            onClick={openPrintableResume}
            className="px-3 py-1.5 rounded-xl text-xs font-semibold bg-zinc-100 hover:bg-zinc-200 text-zinc-800 inline-flex items-center gap-1.5 transition-colors cursor-pointer"
          >
            <FileText className="w-3.5 h-3.5 text-zinc-600" />
            <span>Save as PDF</span>
          </button>
        </div>
      </div>

      {/* Grid: Credentials & Experience */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Left Col: Pedigree & Target Preferences */}
        <div className="space-y-6">
          
          {/* Education */}
          <div className="bg-white rounded-2xl border border-zinc-200 p-5 shadow-xs">
            <div className="flex items-center gap-2 font-bold text-sm text-zinc-900 mb-3">
              <GraduationCap className="w-4 h-4 text-indigo-600" />
              <span>Academic Pedigree</span>
            </div>
            <div className="p-3.5 rounded-xl bg-zinc-50 border border-zinc-100">
              <div className="font-bold text-sm text-zinc-900">{SHIKHAR_PROFILE.education.institution}</div>
              <div className="text-xs text-indigo-700 font-semibold mt-0.5">{SHIKHAR_PROFILE.education.degree}</div>
              <div className="text-xs text-zinc-500 mt-0.5">{SHIKHAR_PROFILE.education.field} • Class of {SHIKHAR_PROFILE.education.gradYear}</div>
              <div className="text-xs font-mono text-zinc-600 mt-1">GPA: {SHIKHAR_PROFILE.education.gpa}</div>
              <div className="mt-2.5 pt-2 border-t border-zinc-200/60 space-y-1">
                {SHIKHAR_PROFILE.education.highlights.map((item, idx) => (
                  <div key={idx} className="text-[11px] text-zinc-600 flex items-start gap-1.5">
                    <span className="text-indigo-500 font-bold">•</span>
                    <span>{item}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Target Parameters */}
          <div className="bg-white rounded-2xl border border-zinc-200 p-5 shadow-xs">
            <div className="flex items-center gap-2 font-bold text-sm text-zinc-900 mb-3">
              <Briefcase className="w-4 h-4 text-emerald-600" />
              <span>Job Search Preferences</span>
            </div>
            <div className="space-y-3 text-xs">
              <div>
                <span className="text-zinc-500 block">Target Roles:</span>
                <div className="flex flex-wrap gap-1.5 mt-1">
                  {SHIKHAR_PROFILE.targetRoles.map(r => (
                    <span key={r} className="px-2 py-0.5 rounded-md bg-zinc-100 text-zinc-800 font-medium">
                      {r}
                    </span>
                  ))}
                </div>
              </div>

              <div>
                <span className="text-zinc-500 block">Target Locations (Bengaluru Hubs):</span>
                <div className="flex flex-wrap gap-1.5 mt-1">
                  {SHIKHAR_PROFILE.targetLocations.map(loc => (
                    <span key={loc} className="px-2 py-0.5 rounded-md bg-indigo-50 text-indigo-700 font-medium border border-indigo-100">
                      {loc}
                    </span>
                  ))}
                </div>
              </div>

              <div>
                <span className="text-zinc-500 block">Target CTC Expectation:</span>
                <span className="font-bold text-zinc-900 text-sm mt-0.5 block">{SHIKHAR_PROFILE.targetCtc}</span>
              </div>
            </div>
          </div>

        </div>

        {/* Center & Right Col: Experience & Technical Arsenal */}
        <div className="lg:col-span-2 space-y-6">
          
          {/* Technical Skills Stack */}
          <div className="bg-white rounded-2xl border border-zinc-200 p-5 shadow-xs">
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-2 font-bold text-sm text-zinc-900">
                <Code2 className="w-4 h-4 text-indigo-600" />
                <span>Technical Stack & Architecture</span>
              </div>
              <span className="text-[11px] text-zinc-400 font-mono">6+ Years Backend Depth</span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
              <div className="p-3 rounded-xl bg-zinc-50 border border-zinc-100">
                <span className="font-bold text-zinc-700 block mb-1.5">Languages & Frameworks:</span>
                <div className="flex flex-wrap gap-1">
                  {[...SHIKHAR_PROFILE.skills.languages, ...SHIKHAR_PROFILE.skills.frameworks].map(s => (
                    <span key={s} className="px-2 py-0.5 rounded-md bg-white border border-zinc-200 text-zinc-800 font-mono text-[11px]">
                      {s}
                    </span>
                  ))}
                </div>
              </div>

              <div className="p-3 rounded-xl bg-zinc-50 border border-zinc-100">
                <span className="font-bold text-zinc-700 block mb-1.5">Databases & Queues:</span>
                <div className="flex flex-wrap gap-1">
                  {SHIKHAR_PROFILE.skills.databases.map(s => (
                    <span key={s} className="px-2 py-0.5 rounded-md bg-white border border-zinc-200 text-zinc-800 font-mono text-[11px]">
                      {s}
                    </span>
                  ))}
                </div>
              </div>

              <div className="p-3 rounded-xl bg-zinc-50 border border-zinc-100 sm:col-span-2">
                <span className="font-bold text-zinc-700 block mb-1.5">Cloud, DevOps & Distributed Architecture:</span>
                <div className="flex flex-wrap gap-1">
                  {[...SHIKHAR_PROFILE.skills.cloudAndDevOps, ...SHIKHAR_PROFILE.skills.architecture].map(s => (
                    <span key={s} className="px-2 py-0.5 rounded-md bg-indigo-50 border border-indigo-100 text-indigo-800 font-mono text-[11px]">
                      {s}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Current Experience Highlights */}
          <div className="bg-white rounded-2xl border border-zinc-200 p-5 shadow-xs">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2 font-bold text-sm text-zinc-900">
                <Award className="w-4 h-4 text-amber-500" />
                <span>Quantified Engineering Highlights</span>
              </div>
              <span className="text-xs text-indigo-600 font-bold">msg global (Nexontis) • PaPM Cloud</span>
            </div>

            <div className="space-y-2.5 text-xs text-zinc-700">
              {SHIKHAR_PROFILE.highlights.map((h, i) => (
                <div key={i} className="flex items-start gap-2.5 p-2.5 rounded-xl bg-zinc-50 border border-zinc-100">
                  <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
                  <span>{h}</span>
                </div>
              ))}
            </div>
          </div>

          {/* ATS Resume Raw Text Drawer */}
          <div className="bg-white rounded-2xl border border-zinc-200 p-5 shadow-xs">
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-2 font-bold text-sm text-zinc-900">
                <Terminal className="w-4 h-4 text-zinc-600" />
                <span>Plaintext ATS Resume (For Direct Portals / Naukri / LinkedIn)</span>
              </div>
              <button
                onClick={handleCopyResume}
                className="px-3 py-1.5 rounded-lg text-xs font-semibold bg-zinc-100 hover:bg-zinc-200 text-zinc-800 transition-colors inline-flex items-center gap-1.5 cursor-pointer"
              >
                {copiedResume ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-600" />
                    <span>Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    <span>Copy Raw Text</span>
                  </>
                )}
              </button>
            </div>

            <div className="max-h-48 overflow-y-auto bg-zinc-900 text-zinc-300 font-mono text-[11px] p-4 rounded-xl leading-relaxed whitespace-pre-wrap border border-zinc-800">
              {RESUME_RAW_TEXT}
            </div>
          </div>

        </div>

      </div>

    </div>
  );
};
